"""Added user and workout and exercise relationships

Revision ID: 8169f501c685
Revises: 4719c48472d6
Create Date: 2026-06-26 20:11:48.798484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8169f501c685'
down_revision: Union[str, Sequence[str], None] = '4719c48472d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercises', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'user_id')
    # ### end Alembic commands ###
