"""add exercise soft delete fields

Revision ID: a6fb9c5cbf82
Revises: 752738d2ffbf
Create Date: 2026-06-24 16:02:49.145541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fb9c5cbf82'
down_revision: Union[str, Sequence[str], None] = '752738d2ffbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('exercises', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'is_active')
    op.drop_column('exercises', 'is_default')
    # ### end Alembic commands ###
